#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Diffract one-shot VPS installer.
#
# Run on a FRESH Ubuntu/Debian VPS (as root). It installs every prerequisite
# (Docker, Node 22 via NVM, git/jq/socat/caddy deps), clones the Diffract repo,
# then runs setup.sh — which builds the Hermes base image locally (mcp/pty/chromium
# baked in), installs the CLI + helper scripts, and wires systemd + Caddy.
#
# USAGE (with a domain → automatic HTTPS):
#   curl -fsSL https://raw.githubusercontent.com/riaan-attar/diffract-main/main/install.sh | bash -s -- yourdomain.com
#
# USAGE (no domain → serves on http://<vps-ip>):
#   curl -fsSL https://raw.githubusercontent.com/riaan-attar/diffract-main/main/install.sh | bash
#
# OVERRIDES (environment variables):
#   DIFFRACT_DOMAIN          domain for HTTPS (same as the 1st positional arg)
#   DIFFRACT_REPO            git URL    (default https://github.com/riaan-attar/diffract-main)
#   DIFFRACT_BRANCH          branch     (default main)
#   DIFFRACT_DIR             install dir (default /root/diffract-main) — keep it stable;
#                            systemd units bake absolute paths to it
#   GITHUB_TOKEN             PAT, required only if the repo is private
#   DIFFRACT_ADMIN_PASSWORD  set the dashboard admin password (else autogenerated)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

DOMAIN="${1:-${DIFFRACT_DOMAIN:-}}"
REPO="${DIFFRACT_REPO:-https://github.com/riaan-attar/diffract-main}"
BRANCH="${DIFFRACT_BRANCH:-main}"
DIR="${DIFFRACT_DIR:-/root/diffract-main}"
NODE_MAJOR=22

log()  { echo -e "\033[0;34m[diffract-install]\033[0m $*"; }
ok()   { echo -e "\033[0;32m✓\033[0m $*"; }
warn() { echo -e "\033[1;33m⚠\033[0m $*"; }
die()  { echo -e "\033[0;31m✗ $*\033[0m" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root — a fresh VPS install needs it. Try: sudo bash"
command -v apt-get >/dev/null 2>&1 || die "This installer targets Debian/Ubuntu (apt-get not found)."

export DEBIAN_FRONTEND=noninteractive

# ── 1. Base packages ────────────────────────────────────────────────────────
log "Installing base packages (git, curl, jq, socat, build tools)…"
apt-get update -y
apt-get install -y ca-certificates curl git jq socat gnupg openssl binutils \
    build-essential apt-transport-https lsb-release
ok "Base packages installed"

# ── 2. Docker (required: the agent runs in an OpenShell sandbox container, and
#       setup.sh builds the base image) ──────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
    log "Installing Docker…"
    curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker 2>/dev/null || true
docker ps >/dev/null 2>&1 || die "Docker is installed but the daemon isn't running. Start it and re-run."
ok "Docker ready"

# ── 3. NVM + Node 22 (root) — setup.sh expects Node 22 and sources /root/.nvm ─
export NVM_DIR="/root/.nvm"
if [ ! -s "$NVM_DIR/nvm.sh" ]; then
    log "Installing NVM…"
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
fi
# shellcheck disable=SC1091
. "$NVM_DIR/nvm.sh"
if ! nvm use "$NODE_MAJOR" >/dev/null 2>&1; then
    log "Installing Node $NODE_MAJOR…"
    nvm install "$NODE_MAJOR"
    nvm use "$NODE_MAJOR"
fi
ok "Node $(node -v)"

# ── 4. Clone (or update) the repo ────────────────────────────────────────────
CLONE_URL="$REPO"
if [ -n "${GITHUB_TOKEN:-}" ]; then
    # Inject a PAT for a private repo without printing it.
    CLONE_URL="https://${GITHUB_TOKEN}@${REPO#https://}"
fi
if [ -d "$DIR/.git" ]; then
    log "Updating existing checkout at $DIR…"
    git -C "$DIR" remote set-url origin "$CLONE_URL" 2>/dev/null || true
    git -C "$DIR" fetch --depth=1 origin "$BRANCH"
    git -C "$DIR" checkout -B "$BRANCH" "origin/$BRANCH"
    git -C "$DIR" reset --hard "origin/$BRANCH"
else
    log "Cloning $REPO ($BRANCH) → $DIR…"
    git clone --branch "$BRANCH" --depth=1 "$CLONE_URL" "$DIR" \
        || die "Clone failed. If the repo is private, set GITHUB_TOKEN=<pat> and re-run."
fi
# Scrub any token from the stored remote so it isn't left on disk.
git -C "$DIR" remote set-url origin "$REPO" 2>/dev/null || true
ok "Repo at $DIR"

# ── 5. Run the unified setup (builds base image, CLI, scripts, services, Caddy) ─
cd "$DIR"
log "Running setup.sh — first run builds the base image (~several minutes)…"
if [ -n "$DOMAIN" ]; then
    bash setup.sh "$DOMAIN"
else
    bash setup.sh --vps
fi

# ── 6. Next steps ────────────────────────────────────────────────────────────
IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
cat <<DONE

────────────────────────────────────────────────────────────────────────────
 ✓ Diffract install complete.

 Open the dashboard:
$( [ -n "$DOMAIN" ] && echo "     https://$DOMAIN   (point this domain's DNS A record at ${IP:-this server})" \
                    || echo "     http://${IP:-<your-vps-ip>}" )

 Log in with the admin password printed by setup.sh above
 (also stored root-only in /etc/diffractui.env).

 Then in the dashboard: Deploy your agent (choose a provider + paste its API key).
 The first Deploy creates the sandbox from the LOCALLY-BUILT base image, so the
 mcp SDK is present and MCP servers + tools work in chat — no manual rebuild.
────────────────────────────────────────────────────────────────────────────
DONE
